apiVersion: 1

policies:
  - receiver: ms-teams
    group_by: ['alertname', 'job']
    repeat_interval: 3h
    group_interval: 5m
    routes:
      - receiver: ms-teams
        matchers:
          - severity =~ "critical|warning|info"
        continue: true
