global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'teams'

receivers:
- name: 'teams'
  webhook_configs:
  - url: 'http://webhook-adapter:8080/alert'
    send_resolved: true

inhibit_rules:
  - source_matchers:
      - severity = 'critical'
    target_matchers:
      - severity = 'warning'
    equal: ['alertname']
