global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 10s
  sample_limit: 1000

# Rule files 
rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  # Prometheus
  - job_name: 'prometheus'
    sample_limit: 50000
    static_configs:
      - targets: ['prometheus:9090']

  # Loki metrics
  - job_name: 'loki'
    sample_limit: 50000
    static_configs:
      - targets: ['loki:3100']

  # Grafana metrics
  - job_name: 'grafana'
    sample_limit: 50000
    static_configs:
      - targets: ['grafana:3000']

  # Node metrics from Alloy - with custom instance name
  - job_name: 'node'
    sample_limit: 50000
    static_configs:
      - targets: ['alloy:12345']
        labels:
          instance: 'main-server'  # Use any name you want
    metrics_path: /metrics

  # Remote node for the second server
  - job_name: 'node-app-server01'
    sample_limit: 50000
    static_configs:
      - targets: ['10.249.84.41:12345']
        labels:
          instance: 'app-server-01'  # Use any name you want
    metrics_path: /metrics
